### ISSUE TITLE
Spark 

### ISSUE THREAD

**Issue by guptaat** [ironmussa/Optimus#1213] opened 2021-11-02 18:56 UTC
Existing Spark session not recognized by optimus

**To Reproduce**
Run the following code. 

> from pyspark.sql import SparkSession
>   spark1 = SparkSession.builder.appName('abcs').getOrCreate()
>   
>   df=spark1.read.csv(r'C:\Users\Downloads\foo.csv',header=True)
>   
>   op= Optimus(spark1)
>  

**Expected behavior**
existing spark dataframes are expected to have optimus functionality. Instead optimus throws an error indicating engine must be text word spark and not spark object session.

**Screenshots**
![image](https://user-images.githubusercontent.com/43218708/139927609-a73dfbaf-7c3a-455e-9235-2cd6d7f7e1d9.png)

**environment**
Latest version from github 21.9 branch.

**Additional context**
Follow up to an issue that was closed some time back https://github.com/hi-primus/optimus/issues/645

**Comment by argenisleon** [comment] 2021-11-03 16:27
Hi @guptaat ,

Can you please try the 2.2.32 version using 'pip install optimuspyspark'?
The actual branch get a heavy refractory and some function needs  extra work to make it compatible with 2.2.23
You can find documentation in the readme section https://github.com/hi-primus/optimus/tree/branch-2.2
Please let me know if it helps.

**Comment by Amangoel998** [comment] 2022-02-08 22:59
Hi @argenisleon,
Can you tell if the issue is fixed in new release or 2.2.32 version code has been merged to latest release?

**Comment by argenisleon** [comment] 2022-02-08 23:46
Hi @Amangoel998,

In the latest release, you can:

`Optimus("spark", session=your_spark_session)`

Please, let me know if it helps

**Closed as completed** 2022-04-14 22:28 UTC
